# This file was generated by GoReleaser. DO NOT EDIT.
cask "tforganize" do
  name "tforganize"
  desc "A CLI tool to sort and organize Terraform files"
  homepage "https://github.com/dthagard/tforganize"
  version "2.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tforganize"

  on_macos do
    on_intel do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_darwin_amd64.tar.gz"
      sha256 "85918c7df90bc37ff65af4a7e853b7b618f23197a06b0a83fe7dcf5f9ac01622"
    end
    on_arm do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_darwin_arm64.tar.gz"
      sha256 "11591ba9db8b8aa84d293ca224d4d84f13c4fb79869a1ad86b9f647d0ce58c28"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_linux_amd64.tar.gz"
      sha256 "4441a55c6347150b55febddef94edc55d836af287b11abd35554325fe90c9e64"
    end
    on_arm do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_linux_arm64.tar.gz"
      sha256 "1b488383d88e9e2b54bed697845fa59db72e96a85f06c649a2dcfcd47f6de8ac"
    end
  end

  # No zap stanza required
end
