# This file was generated by GoReleaser. DO NOT EDIT.
cask "tforganize" do
  name "tforganize"
  desc "A CLI tool to sort and organize Terraform files"
  homepage "https://github.com/dthagard/tforganize"
  version "2.0.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "tforganize"

  on_macos do
    on_intel do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_darwin_amd64.tar.gz"
      sha256 "9fc471df67192c63424da23d5f45a503d4c2ce20596cd681085cd273ca0ed10c"
    end
    on_arm do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_darwin_arm64.tar.gz"
      sha256 "d6594a73bf959471680ae9b7d026c0204abbb5157771b42b785eb59a006ce339"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_linux_amd64.tar.gz"
      sha256 "602f7466987d88f00762259981ac56d83b37d97413916e531b86b4d7176d4fe3"
    end
    on_arm do
      url "https://github.com/dthagard/tforganize/releases/download/v#{version}/tforganize_#{version}_linux_arm64.tar.gz"
      sha256 "98004043ec67e5b14e32d0d3b4750c034f050e20c6f0fed961748296db1fffe5"
    end
  end

  # No zap stanza required
end
